<?php

/**
 * SendGrid Inbound Parse shaped payload for testing lead extraction.
 *
 * @return array<string, mixed>
 */
return function (string $toAddress): array {
    $subject = 'New lead: 2024 Sea Ray SLX 280 — John Martinez';

    $text = <<<'TEXT'
---------- Forwarded message ---------
From: Boat Trader Leads <leads@boattrader.com>
Date: Tue, Jun 10, 2026 at 2:14 PM
Subject: New inquiry for 2024 Sea Ray SLX 280
To: sales@exampledealer.com

You have a new lead from Boat Trader.

Customer name: John Martinez
Email: john.martinez@email.com
Phone: (239) 555-0182
Company: Martinez Family Holdings

Boat of interest: 2024 Sea Ray SLX 280
Listing price: $189,500
Location: Naples, FL

Message from buyer:
Hi, I'm interested in scheduling a sea trial this weekend if the boat is still available. We may have a trade-in (2018 Cobalt R5). Please call or email me back.

Thanks,
John

---
This lead was generated by Boat Trader. Do not reply to this automated message.

Boat Trader Customer Care
1-800-555-BOAT
TEXT;

    return [
        'headers' => "Received: by inbound.helmful.com; Tue, 10 Jun 2026 18:14:22 +0000\r\n",
        'dkim' => '{@boattrader.com : pass}',
        'to' => $toAddress,
        'from' => 'Boat Trader Leads <leads@boattrader.com>',
        'subject' => $subject,
        'text' => $text,
        'html' => '<p>'.nl2br(htmlspecialchars($text, ENT_QUOTES, 'UTF-8')).'</p>',
        'sender_ip' => '167.89.0.1',
        'envelope' => json_encode([
            'to' => [$toAddress],
            'from' => 'leads@boattrader.com',
        ], JSON_THROW_ON_ERROR),
        'charsets' => '{"to":"UTF-8","from":"UTF-8","subject":"UTF-8","text":"UTF-8","html":"UTF-8"}',
        'SPF' => 'pass',
    ];
};
